"""Static demo UI service.

Serves `ui/` and one generated file, `/config.js`, which publishes the
capability API's browser-reachable base URL. The browser then calls the API
directly, so this service carries no API traffic and needs no knowledge of
the capability contract.

Deployment note: `API_ENDPOINT` reaches the browser, so it must be the URL a
browser can resolve (a public gateway hostname), not an internal service name.
"""

from __future__ import annotations

import json
import logging

from fastapi import FastAPI, HTTPException, Response, status
from fastapi.staticfiles import StaticFiles

from control_translation_ui.config import UISettings, get_ui_settings

logger = logging.getLogger(__name__)

app = FastAPI(
    title="control-translation demo UI",
    version="0.1.0",
    description=(
        "Static demo UI for the control-translation capability. Configured "
        "with API_ENDPOINT; holds no capability state or credentials."
    ),
    docs_url=None,
    redoc_url=None,
    openapi_url=None,
)

_SETTINGS: UISettings = get_ui_settings()


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/ready")
def readiness() -> dict[str, object]:
    """Readiness plus the resolved API endpoint, which is not a secret."""
    if not _SETTINGS.ready:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "not-ready",
                "configuration_errors": _SETTINGS.configuration_errors,
            },
        )
    return {
        "status": "ready",
        "api_endpoint": _SETTINGS.normalized_api_endpoint,
    }


@app.get("/config.js")
def runtime_config() -> Response:
    """Publish the API endpoint to the browser as a tiny JS module.

    Generated per request and served `no-store` so that repointing the UI at a
    different API is a restart, never a cache eviction problem.
    """
    payload = json.dumps(
        {"apiEndpoint": _SETTINGS.normalized_api_endpoint},
        ensure_ascii=True,
    )
    body = (
        "// Generated by the control-translation UI service. Do not edit.\n"
        f"window.CONTROL_TRANSLATION_CONFIG = Object.freeze({payload});\n"
    )
    return Response(
        content=body,
        media_type="application/javascript",
        headers={"Cache-Control": "no-store"},
    )


if _SETTINGS.static_dir.is_dir():
    # Mounted last so /health, /ready, and /config.js keep precedence.
    app.mount(
        "/",
        StaticFiles(directory=str(_SETTINGS.static_dir), html=True),
        name="ui",
    )
else:  # pragma: no cover - configuration error surfaced by /ready
    logger.error(
        "UI static directory not found static_dir=%s", _SETTINGS.static_dir
    )
