name: Trigger DevOps Docker Publish

on:
  push:
    branches:
      - main

jobs:
  trigger-devops:
    runs-on: concordia-linux-cpu2-ram7gi

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Print trigger information
        run: |
          echo "======================================"
          echo " Triggering Central CI/CD"
          echo "======================================"
          echo "Source Repository : ${{ github.repository }}"
          echo "Branch            : ${{ github.ref_name }}"
          echo "Commit SHA        : ${{ github.sha }}"
          echo "Triggered By      : ${{ github.actor }}"
          echo "Workflow          : ${{ github.workflow }}"
          echo "Run ID            : ${{ github.run_id }}"
          echo ""
          echo "Images:"
          echo " control-translation"
          echo ""
          echo "Target Repository : amp0047460-devop"
          echo "Event Type        : feature-build"
          echo "======================================"

      - name: Trigger amp0047460-devop
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'amp0047460-devop',
              event_type: 'feature-build',

              client_payload: {
                repository: context.repo.owner + '/apm0047460-Janus-control-translation',
                ref: context.ref.replace('refs/heads/', ''),
                sha: context.sha,
                triggered_by: context.actor,

                images: [
                  {
                    name: 'janus-control-translation/control-translation',
                    tag: 'latest'
                  },
                ]
              }
            });

            console.log('repository_dispatch sent successfully');
            console.log('Target: amp0047460-devop');
            console.log('Event: feature-build');